#!/usr/bin/env python3
"""MOGO-011 Step 2 -- retry policy, attempt semantics, backoff and eligibility.

Pure stdlib (unittest). Fully offline, deterministic, repeatable. Every test
that touches state uses a tempfile state root; no test sleeps.

WHY NOTHING SLEEPS, AND WHY THAT IS NOT A SHORTCUT
    The runtime never waits: `run` is one-shot and releases whatever is
    eligible now. A test that wants to observe a release advances an INJECTED
    clock and calls `run` again. The eligibility comparison the runtime makes
    is identical either way -- what the injection removes is the waiting, not
    the check. `test_a_retry_is_not_released_before_its_eligibility` proves the
    rule bites by leaving the clock alone and asserting nothing is released.

Run with:
    python3 -m unittest tests.platform.test_runtime_retry -v
"""

import json
import os
import sys
import tempfile
import unittest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC_DIR = os.path.join(REPO_ROOT, "platform", "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

from mogo_platform.contracts import command as command_contract  # noqa: E402
from mogo_platform.contracts import errors as contract_errors  # noqa: E402
from mogo_platform.contracts import ids  # noqa: E402
from mogo_platform.runtime import clock as clock_module  # noqa: E402
from mogo_platform.runtime import cli as cli_module  # noqa: E402
from mogo_platform.runtime import errors as runtime_errors  # noqa: E402
from mogo_platform.runtime import orchestrator as orchestrator_module  # noqa: E402
from mogo_platform.runtime import paths as paths_module  # noqa: E402
from mogo_platform.runtime import retry  # noqa: E402

# Independently transcribed from Catalog section K, NOT imported from the
# implementation: (retryable, terminal, routesToReview) per class.
CATALOG_SECTION_K = {
    "transient":                (True,  False, False),
    "rate_limited":             (True,  False, False),
    "dependency_unavailable":   (True,  False, False),
    "authentication":           (False, True,  True),
    "policy_blocked":           (False, True,  True),
    "not_found":                (False, True,  False),
    "validation":               (False, True,  False),
    "deterministic_processing": (False, True,  True),
    "corrupted_input":          (False, True,  True),
    "permanent":                (False, True,  False),
    "source_mutated":           (False, False, True),
    "human_review_required":    (False, False, True),
}

# Independently transcribed from Step 2 plan section 9.1, computed by hand from
# min(1000 * 2 ** (attempt - 1), 60000) + 0. NOT generated by the code under
# test -- a table produced by the implementation would prove only that the
# implementation equals itself.
EXPECTED_BACKOFF_TABLE = {
    1: 1000, 2: 2000, 3: 4000, 4: 8000, 5: 16000,
    6: 32000, 7: 60000, 8: 60000, 9: 60000, 10: 60000,
}

DEFAULT_POLICY = {"attemptLimit": 3, "backoffBaseMs": 1000,
                  "backoffMultiplier": 2, "backoffCapMs": 60000, "jitterMs": 0}


class TestRetryabilityReadsOneTable(unittest.TestCase):
    def test_the_committed_table_matches_the_catalog(self):
        self.assertEqual(set(contract_errors.ERROR_CLASSES), set(CATALOG_SECTION_K))
        for name, (retryable, terminal, review) in CATALOG_SECTION_K.items():
            with self.subTest(error_class=name):
                record = contract_errors.ERROR_CLASSES[name]
                self.assertEqual(record["retryable"], retryable)
                self.assertEqual(record["terminal"], terminal)
                self.assertEqual(record["routesToReview"], review)

    def test_is_retryable_agrees_with_the_catalog_for_every_class(self):
        for name, (retryable, _t, _r) in CATALOG_SECTION_K.items():
            with self.subTest(error_class=name):
                self.assertEqual(retry.is_retryable(name), retryable)

    def test_no_error_class_name_is_hard_coded_as_a_retryable_literal(self):
        """The retry module must consult the table, never restate it.

        A second list of retryable class names is a second place to be wrong,
        and the two would drift silently. `policy_blocked` is the ONE permitted
        literal, because Constitution section 11 singles it out and the guard
        must work even if the table were mutated.
        """
        import inspect
        source = inspect.getsource(retry)
        for name in CATALOG_SECTION_K:
            if name == "policy_blocked":
                continue
            with self.subTest(error_class=name):
                self.assertNotIn('"%s"' % name, source)
                self.assertNotIn("'%s'" % name, source)

    def test_policy_blocked_is_not_retryable_in_the_contract_table(self):
        self.assertFalse(contract_errors.ERROR_CLASSES["policy_blocked"]["retryable"])


class TestClassifyFailure(unittest.TestCase):
    def test_a_retryable_failure_schedules_a_retry(self):
        for name in ("transient", "rate_limited", "dependency_unavailable"):
            with self.subTest(error_class=name):
                decision = retry.classify_failure(name, 1, 3)
                self.assertTrue(decision.retry)
                self.assertEqual(decision.reason, "retryable_within_attempt_limit")

    def test_a_non_retryable_failure_does_not_schedule_a_retry(self):
        for name in ("authentication", "not_found", "validation",
                     "deterministic_processing", "corrupted_input", "permanent"):
            with self.subTest(error_class=name):
                decision = retry.classify_failure(name, 1, 3)
                self.assertFalse(decision.retry)
                self.assertEqual(decision.reason, "non_retryable_error_class")

    def test_policy_blocked_never_retries(self):
        for attempt in range(0, 12):
            with self.subTest(attempt=attempt):
                decision = retry.classify_failure("policy_blocked", attempt, 10)
                self.assertFalse(decision.retry)
                self.assertEqual(decision.reason, "policy_denial_never_retried")

    def test_policy_denial_is_refused_even_if_the_table_says_retryable(self):
        """Guard 2, proved independent of guard 1.

        The table is monkeypatched to claim a policy denial is retryable. The
        decision must still refuse, because the guard is checked BEFORE the
        table is consulted. Constitution section 11: retrying a policy denial
        is an attempt to launder it, so one guard is not enough.
        """
        original = contract_errors.ERROR_CLASSES
        patched = dict(original)
        patched["policy_blocked"] = {"retryable": True, "terminal": False,
                                     "routesToReview": False}
        contract_errors.ERROR_CLASSES = patched
        try:
            decision = retry.classify_failure("policy_blocked", 1, 3)
            self.assertFalse(decision.retry)
            self.assertEqual(decision.reason, "policy_denial_never_retried")
        finally:
            contract_errors.ERROR_CLASSES = original
        self.assertIs(contract_errors.ERROR_CLASSES, original)

    def test_an_unknown_error_class_is_not_retryable(self):
        for name in ("", "not_a_class", "TRANSIENT", None, "transient "):
            with self.subTest(error_class=name):
                decision = retry.classify_failure(name, 1, 3)
                self.assertFalse(decision.retry)
                self.assertEqual(decision.reason, "unknown_error_class")

    def test_a_review_routing_class_has_nowhere_legal_to_go(self):
        for name in ("source_mutated", "human_review_required"):
            with self.subTest(error_class=name):
                self.assertTrue(retry.requires_review_gate(name))
                decision = retry.classify_failure(name, 1, 3)
                self.assertFalse(decision.retry)
                self.assertEqual(decision.reason, "requires_review_no_gate")

    def test_no_failed_to_awaiting_review_edge_exists_in_the_contract(self):
        """The finding decision B-3 rests on, asserted against the contract."""
        from mogo_platform.contracts import task_states
        self.assertEqual(task_states.legal_successors("failed"),
                         ("cancelled", "dead_lettered", "retry_scheduled"))
        self.assertNotIn("awaiting_review", task_states.legal_successors("failed"))

    def test_the_attempt_limit_is_enforced_exactly(self):
        # attemptLimit counts TOTAL attempts, not retries: limit 3 permits
        # 3 executions, i.e. the first plus at most 2 retries.
        cases = {(1, 3): True, (2, 3): True, (3, 3): False, (4, 3): False,
                 (1, 1): False, (1, 2): True, (2, 2): False,
                 (9, 10): True, (10, 10): False}
        for (attempt, limit), should_retry in cases.items():
            with self.subTest(attempt=attempt, limit=limit):
                decision = retry.classify_failure("transient", attempt, limit)
                self.assertEqual(decision.retry, should_retry)
                if not should_retry:
                    self.assertEqual(decision.reason, "attempts_exhausted")

    def test_every_error_class_reaches_the_expected_terminal_reason(self):
        expected = {
            "transient": None, "rate_limited": None, "dependency_unavailable": None,
            "authentication": "non_retryable_error_class",
            "policy_blocked": "policy_denial_never_retried",
            "not_found": "non_retryable_error_class",
            "validation": "non_retryable_error_class",
            "deterministic_processing": "non_retryable_error_class",
            "corrupted_input": "non_retryable_error_class",
            "permanent": "non_retryable_error_class",
            "source_mutated": "requires_review_no_gate",
            "human_review_required": "requires_review_no_gate",
            "invented_class": "unknown_error_class",
        }
        self.assertEqual(len(expected), 13)
        for name, reason in expected.items():
            with self.subTest(error_class=name):
                self.assertEqual(retry.dead_letter_reason(name, 1, 3), reason)

    def test_every_dead_letter_reason_is_declared(self):
        self.assertEqual(len(retry.DEAD_LETTER_REASONS), 5)
        for name in CATALOG_SECTION_K:
            reason = retry.dead_letter_reason(name, 99, 3)
            with self.subTest(error_class=name):
                self.assertIn(reason, retry.DEAD_LETTER_REASONS)


class TestBackoff(unittest.TestCase):
    def test_backoff_matches_the_independently_transcribed_table(self):
        for attempt, expected in EXPECTED_BACKOFF_TABLE.items():
            with self.subTest(attempt=attempt):
                self.assertEqual(retry.backoff_ms(attempt, DEFAULT_POLICY), expected)

    def test_backoff_uses_integer_arithmetic_only(self):
        for attempt in range(1, 21):
            value = retry.backoff_ms(attempt, DEFAULT_POLICY)
            with self.subTest(attempt=attempt):
                self.assertIsInstance(value, int)
                self.assertNotIsInstance(value, float)

    def test_backoff_is_identical_for_identical_inputs(self):
        for attempt in range(1, 11):
            values = {retry.backoff_ms(attempt, DEFAULT_POLICY)
                      for _ in range(1000)}
            with self.subTest(attempt=attempt):
                self.assertEqual(len(values), 1)

    def test_backoff_is_capped(self):
        policy = dict(DEFAULT_POLICY, backoffCapMs=5000)
        for attempt in range(1, 15):
            with self.subTest(attempt=attempt):
                self.assertLessEqual(retry.backoff_ms(attempt, policy), 5000)

    def test_a_multiplier_of_one_is_constant_backoff(self):
        policy = dict(DEFAULT_POLICY, backoffMultiplier=1)
        for attempt in range(1, 10):
            with self.subTest(attempt=attempt):
                self.assertEqual(retry.backoff_ms(attempt, policy), 1000)

    def test_backoff_is_computed_for_a_one_based_attempt(self):
        for bad in (0, -1, True, 1.5, "1", None):
            with self.subTest(attempt=bad):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.backoff_ms(bad, DEFAULT_POLICY)

    def test_jitter_is_zero_and_no_randomness_is_importable(self):
        self.assertEqual(retry.DEFAULT_RETRY_POLICY["jitterMs"], 0)
        with self.assertRaises(runtime_errors.RetryPolicyError):
            retry.validate_policy(dict(DEFAULT_POLICY, jitterMs=25))
        import inspect
        source = inspect.getsource(retry)
        self.assertNotIn("import random", source)
        self.assertNotIn("import secrets", source)

    def test_a_float_multiplier_is_refused_rather_than_coerced(self):
        for bad in (2.0, 1.5, "2", None, True):
            with self.subTest(multiplier=bad):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.validate_policy(dict(DEFAULT_POLICY,
                                               backoffMultiplier=bad))

    def test_a_multiplier_below_one_is_refused(self):
        for bad in (0, -1):
            with self.subTest(multiplier=bad):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.validate_policy(dict(DEFAULT_POLICY,
                                               backoffMultiplier=bad))

    def test_a_negative_policy_value_is_refused(self):
        for field in ("backoffBaseMs", "backoffCapMs", "jitterMs"):
            with self.subTest(field=field):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.validate_policy(dict(DEFAULT_POLICY, **{field: -1}))


class TestAttemptLimitCeiling(unittest.TestCase):
    def test_the_ceiling_is_ten(self):
        self.assertEqual(retry.MAX_ATTEMPT_LIMIT, 10)

    def test_the_default_comes_from_the_committed_contract(self):
        self.assertEqual(retry.DEFAULT_ATTEMPT_LIMIT,
                         command_contract.COMMAND_DEFAULTS["attemptLimit"])
        self.assertEqual(retry.DEFAULT_ATTEMPT_LIMIT, 3)

    def test_a_policy_above_the_ceiling_is_refused(self):
        for limit in (11, 100, 10 ** 6):
            with self.subTest(limit=limit):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.resolve_policy(None, attempt_limit_override=limit)

    def test_a_policy_at_the_ceiling_is_accepted(self):
        self.assertEqual(
            retry.resolve_policy(None, attempt_limit_override=10)["attemptLimit"], 10)

    def test_a_limit_below_one_is_refused(self):
        for limit in (0, -1):
            with self.subTest(limit=limit):
                with self.assertRaises(runtime_errors.RetryPolicyError):
                    retry.resolve_policy(None, attempt_limit_override=limit)

    def test_an_unknown_policy_field_is_refused(self):
        with self.assertRaises(runtime_errors.RetryPolicyError):
            retry.resolve_policy({"backoffBaseMs": 1, "wobbleMs": 3})


class TestEligibility(unittest.TestCase):
    def test_eligibility_is_inclusive_at_the_boundary(self):
        self.assertFalse(retry.is_eligible(1000, 999))
        self.assertTrue(retry.is_eligible(1000, 1000))
        self.assertTrue(retry.is_eligible(1000, 1001))

    def test_a_zero_backoff_is_eligible_at_once(self):
        now = 1_700_000_000_000
        self.assertTrue(retry.is_eligible(retry.next_eligible_at_ms(now, 0), now))

    def test_iso8601_lexical_order_matches_chronological_order(self):
        """The SQL filter compares strings; the Python predicate compares
        integers. If the two orders could disagree, a retry could be released
        by one and withheld by the other."""
        stamps = ["1999-12-31T23:59:59.999Z", "2000-01-01T00:00:00.000Z",
                  "2026-08-08T11:59:59.999Z", "2026-08-08T12:00:00.000Z",
                  "2026-08-08T12:00:00.001Z", "2026-12-31T23:59:59.999Z",
                  "2027-01-01T00:00:00.000Z"]
        by_string = sorted(stamps)
        by_instant = sorted(stamps, key=lambda s: clock_module.parse_iso8601_ms(s))
        self.assertEqual(by_string, by_instant)
        for earlier, later in zip(stamps, stamps[1:]):
            with self.subTest(pair=(earlier, later)):
                self.assertEqual(
                    earlier < later,
                    clock_module.parse_iso8601_ms(earlier)
                    < clock_module.parse_iso8601_ms(later))


class TestClockDiscipline(unittest.TestCase):
    def test_round_trip_is_exact_at_millisecond_precision(self):
        for stamp in ("1970-01-01T00:00:00.000Z", "2026-08-08T12:00:00.001Z",
                      "2026-12-31T23:59:59.999Z"):
            with self.subTest(stamp=stamp):
                self.assertEqual(
                    clock_module.format_ms(clock_module.parse_iso8601_ms(stamp)),
                    stamp)

    def test_a_manual_clock_advances_only_when_told(self):
        clock = clock_module.ManualClock("2026-08-08T12:00:00.000Z")
        self.assertEqual(clock.now_iso(), "2026-08-08T12:00:00.000Z")
        self.assertEqual(clock.now_iso(), "2026-08-08T12:00:00.000Z")
        clock.advance_ms(1500)
        self.assertEqual(clock.now_iso(), "2026-08-08T12:00:01.500Z")

    def test_a_manual_clock_refuses_to_advance_backwards(self):
        clock = clock_module.ManualClock("2026-08-08T12:00:00.000Z")
        with self.assertRaises(runtime_errors.ClockRollbackError):
            clock.advance_ms(-1)

    def test_the_monotonic_floor_accepts_equality_and_refuses_the_past(self):
        floor = clock_module.MonotonicFloor()
        floor.observe("2026-08-08T12:00:00.005Z")
        # Nine events inside one millisecond is normal and must stay legal.
        floor.check("2026-08-08T12:00:00.005Z")
        floor.check("2026-08-08T12:00:00.006Z")
        with self.assertRaises(runtime_errors.ClockRollbackError):
            floor.check("2026-08-08T12:00:00.004Z")

    def test_no_skew_tolerance_is_granted(self):
        floor = clock_module.MonotonicFloor()
        floor.observe("2026-08-08T12:00:00.100Z")
        with self.assertRaises(runtime_errors.ClockRollbackError):
            floor.check("2026-08-08T12:00:00.099Z")   # one millisecond early

    def test_a_naive_datetime_is_refused(self):
        import datetime as datetime_module
        with self.assertRaises(runtime_errors.ContractValidationError):
            clock_module.format_iso8601_ms(datetime_module.datetime(2026, 8, 8))


class RuntimeRetryCase(unittest.TestCase):
    """End-to-end retry behaviour against a real state root and a real log."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.paths = paths_module.RuntimePaths(os.path.join(self._tmp.name, "state"))
        self.clock = clock_module.ManualClock("2026-08-08T12:00:00.000Z")
        self.runtime = orchestrator_module.Orchestrator(
            paths=self.paths, clock=self.clock).open()
        self.runtime.register_builtin_capabilities()

    def tearDown(self):
        self.runtime.close()
        self._tmp.cleanup()

    def submit_retry_task(self, fail_until, note="retry", backoff_base_ms=None):
        """Submit a fail-then-succeed task, optionally with a non-zero backoff.

        The backoff override is applied to the TASK's recorded policy, which is
        exactly where the runtime reads it from -- so this exercises the real
        release path rather than a parallel one.
        """
        envelope, payload = cli_module.build_retry_demo_command(fail_until, note)
        outcome = self.runtime.submit(envelope, payload)
        if backoff_base_ms is not None:
            policy = json.loads(self.runtime.connection.execute(
                "SELECT retry_policy FROM tasks WHERE task_id = ?",
                (outcome.task_id,)).fetchone()[0])
            policy["backoffBaseMs"] = backoff_base_ms
            with self.runtime.connection:
                self.runtime.connection.execute(
                    "UPDATE tasks SET retry_policy = ? WHERE task_id = ?",
                    (json.dumps(policy, sort_keys=True), outcome.task_id))
        return outcome

    def task(self, task_id):
        return self.runtime.connection.execute(
            "SELECT * FROM tasks WHERE task_id = ?", (task_id,)).fetchone()

    def event_types(self, task_id):
        return [row[0] for row in self.runtime.connection.execute(
            "SELECT event_type FROM event_index WHERE task_id = ? "
            "ORDER BY log_sequence", (task_id,))]


class TestRetryEndToEnd(RuntimeRetryCase):
    def test_a_retryable_failure_is_retried_and_then_succeeds(self):
        outcome = self.submit_retry_task(1)
        self.runtime.run_once()
        row = self.task(outcome.task_id)
        self.assertEqual(row["state"], "succeeded")
        self.assertEqual(row["attempt"], 2)
        self.assertEqual(row["terminal"], 1)

    def test_retry_event_ordering_is_exact(self):
        outcome = self.submit_retry_task(1)
        self.runtime.run_once()
        types = self.event_types(outcome.task_id)
        expected = ["TaskRequested", "TaskPolicyCheckRequested", "PolicyEvaluated",
                    "TaskClaimed", "TaskStarted", "TaskFailed",
                    "TaskRetryScheduled", "TaskRetryReleased", "TaskClaimed",
                    "TaskStarted", "TaskSucceeded"]
        self.assertEqual(types, expected)

    def test_attempt_increments_exactly_once_per_execution(self):
        outcome = self.submit_retry_task(2)
        self.runtime.run_once()
        row = self.task(outcome.task_id)
        starts = self.event_types(outcome.task_id).count("TaskStarted")
        self.assertEqual(row["attempt"], starts)
        self.assertEqual(row["attempt"], 3)

    def test_replaying_task_started_does_not_increment_the_attempt(self):
        from mogo_platform.runtime import projection
        outcome = self.submit_retry_task(1)
        self.runtime.run_once()
        before = self.task(outcome.task_id)["attempt"]
        # Replay the WHOLE log from the beginning against the live index.
        projection.replay(self.runtime.connection, self.runtime.log,
                          from_log_sequence=0)
        self.assertEqual(self.task(outcome.task_id)["attempt"], before)

    def test_attempt_is_written_by_exactly_one_sql_statement_in_the_runtime(self):
        """A double increment cannot hide anywhere, because nothing else in the
        runtime touches tasks.attempt.

        AST, not a text scan: a comment explaining the increment is prose, and
        a test that counted prose would fail for the wrong reason -- and could
        be "fixed" by deleting the explanation.
        """
        import ast
        runtime_dir = os.path.join(SRC_DIR, "mogo_platform", "runtime")
        increments, assignments = [], []
        for root, _dirs, files in os.walk(runtime_dir):
            for name in sorted(files):
                if not name.endswith(".py"):
                    continue
                path = os.path.join(root, name)
                with open(path, "r", encoding="utf-8") as handle:
                    tree = ast.parse(handle.read(), filename=path)
                for node in ast.walk(tree):
                    if not (isinstance(node, ast.Constant)
                            and isinstance(node.value, str)):
                        continue
                    if "attempt + 1" in node.value:
                        increments.append((name, node.lineno, node.value))
                    upper = node.value.upper()
                    if "SET ATTEMPT" in upper or "ATTEMPT =" in upper:
                        assignments.append((name, node.lineno, node.value))
        self.assertEqual(len(increments), 1, increments)
        self.assertEqual(increments[0][0], "projection.py")
        # No other statement assigns the column at all.
        self.assertEqual(assignments, [])

    def test_the_idempotency_key_is_identical_across_every_attempt(self):
        outcome = self.submit_retry_task(2)
        before = self.task(outcome.task_id)["idempotency_key"]
        self.runtime.run_once()
        after = self.task(outcome.task_id)
        self.assertEqual(after["attempt"], 3)
        self.assertEqual(after["idempotency_key"], before)

    def test_the_execution_context_is_not_part_of_the_idempotency_key(self):
        """The key is derived from the semantic payload alone.

        `ids.idempotency_key` rejects an undeclared part, so an attempt number
        cannot be smuggled into a key even by mistake -- asserted directly.
        """
        parts = {"inputHash": "a" * 64, "transformationId": "XF|x",
                 "transformationVersion": "1.0.0"}
        base = ids.idempotency_key("transformation", parts)
        self.assertEqual(ids.idempotency_key("transformation", dict(parts)), base)
        with self.assertRaises(contract_errors.IdentifierError):
            ids.idempotency_key("transformation", dict(parts, attempt=2))

    def test_retry_scheduling_is_reconstructable_from_the_log_alone(self):
        outcome = self.submit_retry_task(1)
        self.runtime.run_once()
        scheduled = self._payloads(outcome.task_id, "TaskRetryScheduled")
        self.assertEqual(len(scheduled), 1)
        payload = scheduled[0]
        for field in ("attempt", "attemptLimit", "errorClass", "decisionReason",
                      "backoffMs", "eligibleAtUtc", "scheduledAtUtc",
                      "retryPolicy"):
            self.assertIn(field, payload)
        self.assertEqual(
            sorted(payload["retryPolicy"]),
            ["backoffBaseMs", "backoffCapMs", "backoffMultiplier", "jitterMs"])
        # The schedule is verifiable without knowing which build produced it.
        expected = retry.backoff_ms(payload["attempt"],
                                    dict(payload["retryPolicy"], attemptLimit=3))
        self.assertEqual(payload["backoffMs"], expected)

    def _payloads(self, task_id, event_type):
        return [record.event["payload"]
                for record in self.runtime.log.scan(verify=True).records
                if record.event.get("taskId") == task_id
                and record.event["eventType"] == event_type]

    def test_a_retry_is_not_released_before_its_eligibility(self):
        """The rule bites: a non-zero backoff withholds the release.

        The clock is NOT advanced, so `run_once` must leave the task in
        retry_scheduled and must not spin trying to drive it.
        """
        outcome = self.submit_retry_task(1, note="held", backoff_base_ms=1000)
        self.runtime.run_once()
        row = self.task(outcome.task_id)
        self.assertEqual(row["state"], "retry_scheduled")
        self.assertEqual(row["attempt"], 1)
        self.assertNotIn("TaskRetryReleased", self.event_types(outcome.task_id))

    def test_a_retry_is_released_exactly_at_eligibility(self):
        outcome = self.submit_retry_task(1, note="exact", backoff_base_ms=1000)
        self.runtime.run_once()
        eligible = self.task(outcome.task_id)["retry_eligible_at"]
        eligible_ms = clock_module.parse_iso8601_ms(eligible)

        # One millisecond early: still withheld.
        self.clock.set_to(eligible_ms - 1)
        self.runtime.run_once()
        self.assertEqual(self.task(outcome.task_id)["state"], "retry_scheduled")

        # Exactly at eligibility: released, and the task completes.
        self.clock.set_to(eligible_ms)
        self.runtime.run_once()
        row = self.task(outcome.task_id)
        self.assertEqual(row["state"], "succeeded")
        self.assertIn("TaskRetryReleased", self.event_types(outcome.task_id))

    def test_no_release_precedes_its_eligibility_when_re_derived_from_the_log(self):
        """The evidence is in the log, not in the code.

        This check re-derives the eligibility comparison by scanning the log,
        so it survives the deletion of every in-process assertion.
        """
        self.submit_retry_task(2, note="a")
        self.runtime.run_once()
        scheduled = {}
        releases = 0
        for record in self.runtime.log.scan(verify=True).records:
            event = record.event
            task_id = event.get("taskId")
            if event["eventType"] == "TaskRetryScheduled":
                scheduled.setdefault(task_id, []).append(
                    event["payload"]["eligibleAtUtc"])
            elif event["eventType"] == "TaskRetryReleased":
                releases += 1
                payload = event["payload"]
                self.assertGreaterEqual(payload["observedAtUtc"],
                                        payload["scheduledEligibleAtUtc"])
                self.assertIn(payload["scheduledEligibleAtUtc"],
                              scheduled.get(task_id, []))
        self.assertGreater(releases, 0)

    def test_run_once_terminates_with_zero_backoff_and_a_high_attempt_limit(self):
        """Termination is bounded by the attempt ceiling, not by luck.

        With a zero backoff every retry is eligible immediately and re-enters
        the drivable set, so this is the shape that would spin forever if the
        attempt limit were not enforced.
        """
        envelope, payload = cli_module.build_retry_demo_command(99, "always-fails")
        envelope["attemptLimit"] = 10
        outcome = self.runtime.submit(envelope, payload)
        report = self.runtime.run_once()
        row = self.task(outcome.task_id)
        self.assertEqual(row["state"], "dead_lettered")
        self.assertEqual(row["attempt"], 10)
        self.assertEqual(len(report["dead_lettered"]), 1)

    def test_an_attempt_limit_above_the_ceiling_is_rejected(self):
        envelope, payload = cli_module.build_retry_demo_command(1, "too-many")
        envelope["attemptLimit"] = 11
        outcome = self.runtime.submit(envelope, payload)
        self.assertEqual(outcome.status, "rejected")
        self.assertIn("ceiling", outcome.reason)
        row = self.runtime.connection.execute(
            "SELECT outcome, reason FROM command_submissions "
            "ORDER BY submission_id DESC LIMIT 1").fetchone()
        self.assertEqual(row["outcome"], "rejected")
        self.assertIn("attemptLimit", row["reason"])

    def test_a_command_attempt_limit_is_recorded_and_honoured(self):
        envelope, payload = cli_module.build_retry_demo_command(9, "limit-2")
        envelope["attemptLimit"] = 2
        outcome = self.runtime.submit(envelope, payload)
        self.runtime.run_once()
        row = self.task(outcome.task_id)
        self.assertEqual(row["attempt_limit"], 2)
        self.assertEqual(row["attempt"], 2)
        self.assertEqual(row["state"], "dead_lettered")

    def test_a_capability_declared_limit_applies_when_the_command_declares_none(self):
        outcome = self.submit_retry_task(9, note="capability-limit")
        self.assertEqual(self.task(outcome.task_id)["attempt_limit"], 3)

    def test_the_retry_policy_recorded_at_creation_is_used_later(self):
        """A change to the capability's declared defaults must not alter the
        schedule of a task that is already in flight."""
        outcome = self.submit_retry_task(1, note="frozen-policy")
        recorded = json.loads(self.task(outcome.task_id)["retry_policy"])
        with self.runtime.connection:
            self.runtime.connection.execute(
                "UPDATE capabilities SET retry_policy = ? WHERE capability_id = ?",
                (json.dumps({"attemptLimit": 1, "backoffBaseMs": 999,
                             "backoffMultiplier": 2, "backoffCapMs": 60000,
                             "jitterMs": 0}),
                 "CAP|research|runtime-fail-then-succeed"))
        self.runtime.run_once()
        self.assertEqual(json.loads(self.task(outcome.task_id)["retry_policy"]),
                         recorded)
        self.assertEqual(self.task(outcome.task_id)["state"], "succeeded")


if __name__ == "__main__":
    unittest.main(verbosity=2)
